# Generated by Django 2.2.16 on 2022-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='1', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
