# Generated by Django 2.2.16 on 2022-03-24 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220322_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='incorrect username', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
